export const quasarFontsPath = 'quasar/fonts'
export const quasarAnimationsPath = 'quasar/animations'
export const quasarIconsPath = 'quasar/icons'
export const quasarCssPath = 'quasar/css'
export const quasarBrandPath = 'quasar/brand'
